name: Glue Job Action
description: Run an AWS Glue job.

branding:
  icon: play
  color: purple

inputs:
  job:
    description: |-
      The name of the job definition to use.
    required: true
  arguments:
    description: |-
      The arguments to pass to the job definition.
      You can pass multiple arguments in the form of key=value, separated by newlines.
    required: false

runs:
  using: node20
  main: dist/index.js
